formatter: "markdown table"

version: ">= 0.14.0"

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  show:
    - requirements
    - providers
    - modules
    - inputs
    - outputs
    - resources

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true